initial_quotes = [
    "Just Keep Swimming - Dori",
    "No one can make you feel inferior without your consent. –Eleanor Roosevelt",
    "If you are always trying to be normal, you’ll never know how amazing you can be. – Maya Angelou",
    "The most effective way to do it, is to do it. – Amelia Earhart",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt.",
    "I never dreamed about success. I worked for it. – Estée Lauder",
    "No matter how plain a woman may be, if truth and honesty are written across her face, she will be beautiful.- Eleanor Roosevelt",
    "I’m not afraid of storms, for I’m learning to sail my ship. – Louisa May Alcott",
    "I think beauty come from knowing who you actually are. That’s real beauty to me. – Ellen DeGeneres",
    "You are more powerful than you know; you are beautiful just as you are. –Melissa Etheridge",
    "I can’t think of any better representation of beauty than someone who is unafraid to be herself. –Emma Stone",
    "The most common way people give up their power is by thinking they don’t have any. - Alice Walker",
    "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough. – Oprah Winfrey",
    "Quality is not an act, it is a habit. - Aristotle",
    "The secret of getting ahead is getting started - Mark Twain",
    "Put your heart, mind, and soul into even your smallest acts. This is the secret of success - Swami Sivananda",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "It's not what you look at that matters, it's what you see. - Henry David Thoreau",
    "All of us, at certain moments of our lives, need to take advice and to receive help from other people. - Alexis Carrel",
    "Don't gain the world and lose your soul; wisdom is better than silver or gold. - Bob Marley"
    "Be as you wish to seem. - Socrates"
    "It is far better to grasp the universe as it really is than to persist in delusion, however satisfying and reassuring - Carl Sagan",
    "Personality is an unbroken series of successful gestures. - F. Scott Fitzgerald",
    "Whatever you are, be a good one - Abraham Linccoln",
    "Don't wait. The time will never be just right - Napoleon Hill",
    "If not us, who? If not now, when? - John F Kennedy",
    "Everything you can imagine is real - Pablo Picasso",
    "Life is trying things to see if they work - Ray Bradbury",
    "Do one thing every day that scares you - Eleanor Roosevelt",
    "The power of imagination makes us inifinite - John Muir",
    "Eighty percent of success is showing up - Woody Allen",
    "A jug fills drop by drop - Budda",
    "The obstacle is the path - Zen Proverb",
    "All you need is love - John Lennon",
    "It does not matter how slowly you go as long as you do not stop - Confucius",
    "It is never to late to be what you might have been - Someone",
    "If you try to fail, and succeed, which have you done? - George Carlin",
    "You can’t wait for inspiration. You have to go after it with a club - Jack London",
    "Great spirits have always encountered violent opposition from mediocre minds - Albert Einstein",
    "A diamond is merely a lump of coal that did well under pressure - Someone",
    "Try to be like the turtle – at ease in your own shell - Bill Copeland",
    "There’s never enough time to do all the nothing you want - Bill Watterson",
    "Think of how stupid the average person is, and realize half of them are stupider than that - George Carlin",
    "The reason I talk to myself is because I’m the only one whose answers I accept - George Carlin",
    "What you do speaks so loudly tha I cannot hear what you say - Ralph Waldo Emerson",
    "The best dreams happen when you’re awake. ~Cherie Gilderbloom",
    "A year from now you may wish you had started today - Karen Lamb",
    "Do what you can, where you are, with what you have - Teddy Roosevelt",
    "To avoid criticism, do nothing, say nothing, be nothing - Elbert Hubbard",
    "Do what you love and the money will follow - Marsha Sinetar",
    "The purpose of our lives is to be happy - Dalai Lama",
    "The price of anything is the amount of life you exchange for it - Henry David Thoreau",
    "There are no shortcuts to any place worth going - Beverly Sills",
    "Do not take life too seriously. You will never get out of it alive - Elbert Hubbard",
    "People who think they know everything are a great annoyance to those of us who do - Isaac Asimov",
    "Roses are red, violets are blue, I'm schizophrenic and so am I - Oscar Levant",
    "I always wanted to be somebody, but not I realize I should have been more specific - Lilly Tomlin",
    "Go to Heaven for the climate, Hell for the company - Mark Twain",
    "All generalizations are false, including this one - Mark Twain"

]




