initial_quotes = [
    {'q': "Just Keep Swimming", 'by': " Dori"},
    {'q': "No one can make you feel inferior without your consent", 'by': "Eleanor Roosevelt"},
    {'q': "If you are always trying to be normal, you’ll never know how amazing you can be", 'by': "Maya Angelou"},
    {'q': "The most effective way to do it, is to do it", 'by': "Amelia Earhart"},
    {'q': "The future belongs to those who believe in the beauty of their dreams", 'by': "Eleanor Roosevelt."},
    {'q': "I never dreamed about success. I worked for it", 'by': "Estée Lauder"},
    {'q': "No matter how plain a woman may be, if truth and honesty are written across her face, she will be beautiful", 'by': "Eleanor Roosevelt"},
    {'q': "I’m not afraid of storms, for I’m learning to sail my ship", 'by': "Louisa May Alcott"},
    {'q': "I think beauty come from knowing who you actually are. That’s real beauty to me", 'by': "Ellen DeGeneres"},
    {'q': "You are more powerful than you know; you are beautiful just as you are", 'by': "Melissa Etheridge"},
    {'q': "I can’t think of any better representation of beauty than someone who is unafraid to be herself", 'by': "Emma Stone"},
    {'q': "The most common way people give up their power is by thinking they don’t have any", 'by': " Alice Walker"},
    {'q': "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough", 'by': "Oprah Winfrey"},
    {'q': "Quality is not an act, it is a habit", 'by': " Aristotle"},
    {'q': "The secret of getting ahead is getting started", 'by': " Mark Twain"},
    {'q': "Put your heart, mind, and soul into even your smallest acts. This is the secret of success", 'by': "Swami Sivananda"},
    {'q': "Do not go where the path may lead, go instead where there is no path and leave a trail", 'by': "Ralph Waldo Emerson"},
    {'q': "It's not what you look at that matters, it's what you see", 'by': " Henry David Thoreau"},
    {'q': "All of us, at certain moments of our lives, need to take advice and to receive help from other people", 'by': "Alexis Carrel"},
    {'q': "Don't gain the world and lose your soul; wisdom is better than silver or gold", 'by': "Bob Marley"},
    {'q': "Be as you wish to seem", 'by': " Socrates"},
    {'q': "It is far better to grasp the universe as it really is than to persist in delusion, however satisfying and reassuring", 'by': "Carl Sagan"},
    {'q': "Personality is an unbroken series of successful gestures", 'by': "F. Scott Fitzgerald"},
    {'q': "Whatever you are, be a good one", 'by': " Abraham Linccoln"},
    {'q': "Don't wait. The time will never be just right", 'by': " Napoleon Hill"},
    {'q': "If not us, who? If not now, when?", 'by': " John F Kennedy"},
    {'q': "Everything you can imagine is real", 'by': " Pablo Picasso"},
    {'q': "Life is trying things to see if they work", 'by': " Ray Bradbury"},
    {'q': "Do one thing every day that scares you", 'by': " Eleanor Roosevelt"},
    {'q': "The power of imagination makes us inifinite", 'by': " John Muir"},
    {'q': "Eighty percent of success is showing up", 'by': " Woody Allen"},
    {'q': "A jug fills drop by drop", 'by': " Budda"},
    {'q': "The obstacle is the path", 'by': " Zen Proverb"},
    {'q': "All you need is love", 'by': " John Lennon"},
    {'q': "It does not matter how slowly you go as long as you do not stop", 'by': " Confucius"},
    {'q': "It is never to late to be what you might have been", 'by': " Someone"},
    {'q': "If you try to fail, and succeed, which have you done?", 'by': " George Carlin"},
    {'q': "You can’t wait for inspiration. You have to go after it with a club", 'by': " Jack London"},
    {'q': "Great spirits have always encountered violent opposition from mediocre minds", 'by': " Albert Einstein"},
    {'q': "A diamond is merely a lump of coal that did well under pressure", 'by': " Someone"},
    {'q': "Try to be like the turtle – at ease in your own shell", 'by': " Bill Copeland"},
    {'q': "There’s never enough time to do all the nothing you want", 'by': " Bill Watterson"},
    {'q': "Think of how stupid the average person is, and realize half of them are stupider than that", 'by': " George Carlin"},
    {'q': "The reason I talk to myself is because I’m the only one whose answers I accept", 'by': " George Carlin"},
    {'q': "What you do speaks so loudly tha I cannot hear what you say", 'by': " Ralph Waldo Emerson"},
    {'q': "The best dreams happen when you’re awake", 'by': "Cherie Gilderbloom"},
    {'q': "A year from now you may wish you had started today", 'by': "Karen Lamb"},
    {'q': "Do what you can, where you are, with what you have", 'by': "Teddy Roosevelt"},
    {'q': "To avoid criticism, do nothing, say nothing, be nothing", 'by': "Elbert Hubbard"},
    {'q': "Do what you love and the money will follow", 'by': "Marsha Sinetar"},
    {'q': "The purpose of our lives is to be happy", 'by': "Dalai Lama"},
    {'q': "The price of anything is the amount of life you exchange for it", 'by': "Henry David Thoreau"},
    {'q': "There are no shortcuts to any place worth going", 'by': " Beverly Sills"},
    {'q': "Do not take life too seriously. You will never get out of it alive", 'by': "Elbert Hubbard"},
    {'q': "People who think they know everything are a great annoyance to those of us who do", 'by': "Isaac Asimov"},
    {'q': "Roses are red, violets are blue, I'm schizophrenic and so am I ", 'by': " Oscar Levant"},
    {'q': "I always wanted to be somebody, but now I realize I should have been more specific", 'by': "Lilly Tomlin"},
    {'q': "Go to Heaven for the climate, Hell for the company", 'by': "Mark Twain"},
    {'q': "All generalizations are false, including this one", 'by': "Mark Twain"},

]




